"""多语言本地化系统（i18n）"""

from ASSET.game_data import draw_gradient_bg, cull_dead, get_font

# 多语言支持系统

# 语言包
LANGUAGES = {
    "zh": {
        "equipment": "装备系统",
        "weapon": "武器",
        "armor": "护甲",
        "horse": "马匹",
        "book": "书籍",
        "level": "等级",
        "attack": "攻击力",
        "defense": "防御力",
        "speed": "速度",
        "intelligence": "智力",
        "upgrade": "升级",
        "max_level": "已达到最高等级",
        "not_enough_resources": "资源不足",
        "upgrade_success": "升级成功",
        "back": "返回",
        "resources": "资源",
        "gold": "金币",
        "wood": "木材",
        "stone": "石头",
        "food": "食物",
        "water": "水",
        "time_crystal": "时间水晶",
        "passive_income": "被动收入",
        "tech_tree": "科技树",
        "hero_warehouse": "英雄仓库",
        "shop": "商店",
        "battle": "战斗",
        "map": "地图",
        "achievements": "成就",
        "activities": "活动",
        "settings": "设置",
        "language": "语言",
        "graphics": " graphics",
        "sound": "声音",
        "fullscreen": "全屏",
        "fps_limit": "FPS 限制",
        "volume": "音量",
        "enable_sound": "启用声音",
        "save": "保存",
        "load": "加载",
        "exit": "退出",
        "login": "登录",
        "register": "注册",
        "username": "用户名",
        "password": "密码",
        "confirm_password": "确认密码",
        "login_success": "登录成功",
        "register_success": "注册成功",
        "invalid_credentials": "无效的凭证",
        "username_taken": "用户名已被使用",
        "passwords_mismatch": "密码不匹配",
        "daily_checkin": "每日签到",
        "checkin_success": "签到成功",
        "already_checked_in": "今日已签到",
        "consecutive_days": "连续签到天数",
        "total_checkins": "总签到次数",
        "reward": "奖励",
        "claim_reward": "领取奖励",
        "reward_claimed": "奖励已领取",
        "pvp": "玩家对战",
        "rankings": "排行榜",
        "mini_games": "小游戏",
        "snake": "贪吃蛇",
        "tetris": "俄罗斯方块",
        "minesweeper": "扫雷",
        "breakout": "打砖块",
        "2048": "2048",
        "gobang": "五子棋",
        "push_box": "推箱子",
        "social": "社交",
        "friends": "好友",
        "chat": "聊天",
        "send_message": "发送消息",
        "receive_message": "接收消息",
        "pet_system": "宠物系统",
        "pets": "宠物",
        "feed": "喂食",
        "level_up": "升级",
        "pet_bonus": "宠物加成"
    },
    "en": {
        "equipment": "Equipment System",
        "weapon": "Weapon",
        "armor": "Armor",
        "horse": "Horse",
        "book": "Book",
        "level": "Level",
        "attack": "Attack",
        "defense": "Defense",
        "speed": "Speed",
        "intelligence": "Intelligence",
        "upgrade": "Upgrade",
        "max_level": "Already at maximum level",
        "not_enough_resources": "Not enough resources",
        "upgrade_success": "Upgrade successful",
        "back": "Back",
        "resources": "Resources",
        "gold": "Gold",
        "wood": "Wood",
        "stone": "Stone",
        "food": "Food",
        "water": "Water",
        "time_crystal": "Time Crystal",
        "passive_income": "Passive Income",
        "tech_tree": "Tech Tree",
        "hero_warehouse": "Hero Warehouse",
        "shop": "Shop",
        "battle": "Battle",
        "map": "Map",
        "achievements": "Achievements",
        "activities": "Activities",
        "settings": "Settings",
        "language": "Language",
        "graphics": "Graphics",
        "sound": "Sound",
        "fullscreen": "Fullscreen",
        "fps_limit": "FPS Limit",
        "volume": "Volume",
        "enable_sound": "Enable Sound",
        "save": "Save",
        "load": "Load",
        "exit": "Exit",
        "login": "Login",
        "register": "Register",
        "username": "Username",
        "password": "Password",
        "confirm_password": "Confirm Password",
        "login_success": "Login successful",
        "register_success": "Register successful",
        "invalid_credentials": "Invalid credentials",
        "username_taken": "Username already taken",
        "passwords_mismatch": "Passwords mismatch",
        "daily_checkin": "Daily Check-in",
        "checkin_success": "Check-in successful",
        "already_checked_in": "Already checked in today",
        "consecutive_days": "Consecutive days",
        "total_checkins": "Total check-ins",
        "reward": "Reward",
        "claim_reward": "Claim Reward",
        "reward_claimed": "Reward already claimed",
        "pvp": "PvP",
        "rankings": "Rankings",
        "mini_games": "Mini Games",
        "snake": "Snake",
        "tetris": "Tetris",
        "minesweeper": "Minesweeper",
        "breakout": "Breakout",
        "2048": "2048",
        "gobang": "Gomoku",
        "push_box": "Push Box",
        "social": "Social",
        "friends": "Friends",
        "chat": "Chat",
        "send_message": "Send Message",
        "receive_message": "Receive Message",
        "pet_system": "Pet System",
        "pets": "Pets",
        "feed": "Feed",
        "level_up": "Level Up",
        "pet_bonus": "Pet Bonus"
    },
    "ja": {
        "equipment": "装備システム",
        "weapon": "武器",
        "armor": "防具",
        "horse": "馬",
        "book": "書籍",
        "level": "レベル",
        "attack": "攻撃力",
        "defense": "防御力",
        "speed": "速度",
        "intelligence": "知力",
        "upgrade": "強化",
        "max_level": "最大レベルに到達",
        "not_enough_resources": "資源が不足しています",
        "upgrade_success": "強化成功",
        "back": "戻る",
        "resources": "資源",
        "gold": "金貨",
        "wood": "木材",
        "stone": "石",
        "food": "食べ物",
        "water": "水",
        "time_crystal": "時間のクリスタル",
        "passive_income": "受動的収入",
        "tech_tree": "技術ツリー",
        "hero_warehouse": "英雄倉庫",
        "shop": "ショップ",
        "battle": "戦闘",
        "map": "地図",
        "achievements": "成果",
        "activities": "アクティビティ",
        "settings": "設定",
        "language": "言語",
        "graphics": "グラフィックス",
        "sound": "サウンド",
        "fullscreen": "全画面",
        "fps_limit": "FPS制限",
        "volume": "音量",
        "enable_sound": "サウンドを有効にする",
        "save": "保存",
        "load": "読み込み",
        "exit": "終了",
        "login": "ログイン",
        "register": "登録",
        "username": "ユーザー名",
        "password": "パスワード",
        "confirm_password": "パスワードを確認",
        "login_success": "ログイン成功",
        "register_success": "登録成功",
        "invalid_credentials": "無効な認証情報",
        "username_taken": "ユーザー名は既に使用されています",
        "passwords_mismatch": "パスワードが一致しません",
        "daily_checkin": "毎日チェックイン",
        "checkin_success": "チェックイン成功",
        "already_checked_in": "今日は既にチェックインしています",
        "consecutive_days": "連続日数",
        "total_checkins": "総チェックイン数",
        "reward": "報酬",
        "claim_reward": "報酬を受け取る",
        "reward_claimed": "報酬は既に受け取られています",
        "pvp": "プレイヤー対プレイヤー",
        "rankings": "ランキング",
        "mini_games": "ミニゲーム",
        "snake": "スネーク",
        "tetris": "テトリス",
        "minesweeper": "マインスイーパー",
        "breakout": "ブレイクアウト",
        "2048": "2048",
        "gobang": "五目並べ",
        "push_box": "箱を押す",
        "social": "ソーシャル",
        "friends": "友達",
        "chat": "チャット",
        "send_message": "メッセージを送信",
        "receive_message": "メッセージを受信",
        "pet_system": "ペットシステム",
        "pets": "ペット",
        "feed": "餌を与える",
        "level_up": "レベルアップ",
        "pet_bonus": "ペットボーナス"
    }
}

# 获取翻译
def get_text(key, lang="zh"):
    """获取指定语言的文本"""
    if lang not in LANGUAGES:
        lang = "zh"
    return LANGUAGES.get(lang, LANGUAGES["zh"]).get(key, key)

# 获取支持的语言列表
def get_supported_languages():
    """获取支持的语言列表"""
    return list(LANGUAGES.keys())

# 获取语言名称
def get_language_name(lang_code):
    """获取语言的显示名称"""
    language_names = {
        "zh": "中文",
        "en": "English",
        "ja": "日本語"
    }
    return language_names.get(lang_code, lang_code)
